### ISSUE TITLE
TFS pending changes incorrect

### ISSUE THREAD

**Issue by Swoogan** [dazinator/DnnPackager#6] opened 2015-04-30 20:59 UTC
When adding the NuGet to a project already in TFS, two files getting marked with the `add` pending state, but are not present on the file system:

1. MSBuild.Community.Tasks.ReadMe.md
2. rename.nuspecc

This will cause a checkin to fail, and one has to undo the pending `add` for these two files.

Furthermore, the following files are not added to TFS:

1. after.JE.D2D.Modules.sln.targets
2. before.JE.D2D.Modules.sln.targets

Lastly, `Build.proj` shows up in the Solution under the `.build` folder, but doesn't appear there on the filesystem (unlike the MSBuild.Community.Tasks.* files).

**Comment by dazinator** [comment] 2015-04-30 21:26
Hi, thanks for this.

The issues with the 'MSBuild.Community.Tasks.ReadMe.md' and the placing of the 'Build.proj' are actually caused by a NuGet package that I depend on. 

You can replicate them by just installing the NuGet package responsible which is:


The problem with 'MSBuild.Community.Tasks.ReadMe.md' (something I noticed too) and the placing of the 'Build.proj' file are all actually issues with the 'MsBuildTasks' NuGet package (that my NuGet package depends upon) - and are not intrinsically anything to do with my own code / nuget package. 

You can see this by creating a project and just installing the `MSBuildTasks` NuGet package.

`Install-Package MSBuildTasks`

: https://github.com/loresoft/msbuildtasks



I could have removed my dependency on the `MsBuild.Community.Tasks` NuGet package, and instead manually bundled the community tasks stuff inside my own package - but then that makes it harder for people to update their version of `MsBuild.Community.Tasks` independently - so I didn;t want to go down that route.

 that NuGet package and, bundle i
known to me, but actually stems from the MsBuild

**Comment by dazinator** [comment] 2015-04-30 21:34
However the other things are valid issues, and I haven't figured out how to solve them yet!

Basically, I use a powershell script to make some file manipulations, including renaming `rename.nuspecc` and placing `after.[solutionname].sln.targets` and `before.JE.[solutionname].sln.targets` in the correct location - but, as you have discovered, I haven't yet figured out how to inform TFS (from powershell) of those modifications.

I cannot assume that TFS is being used, but I am assuming that there must be away to interface with the current VS source control provider, from the powershell script - but it presently remains beyond me. Until I can solve that, I won't be able to fix this. 

I'll leave this in the backburner for the time being. I do intend to fix it, eventually!

If you have any experience in this department, feel free to lend a hand haha :)

**Comment by Swoogan** [comment] 2015-05-01 13:40
For the before and after targets, you could simply add them to the solution under the `.build` folder. That would automatically add them to source control. On the other hand, if the file is the selected file in the Solution Explorer, you can call

    $dte.ExecuteCommand("File.TfsAddFilesToSourceControl")

However, if it's part of the solution it should already be added, so I don't think that would help.

---

To undo the add of the other files, the best I think that can be done is to call:

     $dte.ExecuteCommand("File.TfsUndoCheckout")

Again, this depends on TFS being there, but you should be able to check that with:

     $dte.Commands.Item("File.TfsUndoCheckout").IsAvailable

However, this is not ideal. It will just pop up the Undo Pending Changes dialog. I think that would be a really confusing event to the user. I don't know of any way to do it silently.

**Comment by dazinator** [comment] 2015-05-17 13:03
> For the before and after targets, you could simply add them to the solution under the .build folder. That would automatically add them to source control. 

Good idea. I think #9 can be addressed at the same time as addressing this. I'll have a go when I get some time, otherwise feel free to send a PR :)

**Comment by dazinator** [comment] 2015-12-15 02:35
>When adding the NuGet to a project already in TFS, two files getting marked with the add pending state, but are not present on the file system:

>1. MSBuild.Community.Tasks.ReadMe.md
2. rename.nuspecc

This is fixed in the latest v2 release. Msbuild.community.tasks is no longer a dependency, and there is no longer a rename.nuspecc file!

In fact it should all be a lot tidier.

However leaving this open as I do still need to add the 2 solution level targets files a solution folder so tfs picks them up.

**Comment by dazinator** [comment] 2016-02-19 01:42
Closing this now because I have been unable to replicate any issues using the TFS with the latest V2 release.

**Closed by dazinator** 2016-02-19 01:42 UTC
